#!/usr/bin/env python3
"""Generate the event-subscription manifest consumed by infra provisioning checks.

The manifest maps each deployed service to the exact set of Pub/Sub topics it
subscribes to in **PubSub / SaaS deployment mode** — i.e. the topics for which a
``${env}-<service>--<topic>`` subscription must exist in the infrastructure
(see caura-memclaw-enterprise ``terraform/.../pubsub``). It is the contract that
lets the enterprise repo's ``check_pubsub_provisioning.py`` fail CI when OSS adds
a consumed topic without the matching Terraform subscription — the gap that took
staging down when ``memclaw.lifecycle.insights-requested`` shipped unprovisioned.

Lifecycle topics are captured **dynamically** by invoking the real registration
helpers against a recording bus, so a new ``bus.subscribe`` added to a helper is
picked up automatically (the manifest-drift test then forces a regen, which the
enterprise check turns into a provisioning requirement).

This script depends only on the ``common`` package (always importable), never on
the per-service packages — OSS CI installs only a subset of them.
"""

from __future__ import annotations

import argparse
import difflib
import json
import sys
from pathlib import Path
from typing import Callable
from unittest import mock

from common.events import lifecycle_handlers
from common.events.topics import Topics

MANIFEST_PATH = (
    Path(__file__).resolve().parent.parent
    / "common"
    / "events"
    / "events_manifest.json"
)

# Memory-pipeline subscriptions are registered by each service's own
# ``register_consumers()`` (core-api/src/core_api/consumer.py and
# core-worker/src/core_worker/consumer.py). They are listed explicitly here
# rather than captured dynamically because OSS CI does not install the worker
# package, so it cannot be imported in this generator. This set is stable; if
# you add a direct ``bus.subscribe`` in a service's register_consumers(), add it
# here too.
_MEMORY_DIRECT: dict[str, list[str]] = {
    "core-api": [str(Topics.Memory.ENRICHED), str(Topics.Memory.EMBEDDED)],
    "core-worker": [
        str(Topics.Memory.EMBED_REQUESTED),
        str(Topics.Memory.ENRICH_REQUESTED),
    ],
}

# Which lifecycle registration helpers each service invokes in PubSub/SaaS mode.
# core-api registers the LLM pipeline ops; core-worker registers the SQL archive
# ops. (In OSS-standalone/InProcess mode core-api also registers the archive ops,
# but that path provisions no Pub/Sub subscriptions, so it is out of scope here.)
_LIFECYCLE_HELPERS: dict[str, list[Callable[[object], None]]] = {
    "core-api": [lifecycle_handlers.register_pipeline_consumers],
    "core-worker": [lifecycle_handlers.register_archive_consumers],
}


class _RecordingBus:
    """Minimal bus stand-in that records the topics passed to ``subscribe``."""

    def __init__(self) -> None:
        self.topics: list[str] = []

    def subscribe(self, topic: str, handler: object) -> None:
        self.topics.append(str(topic))


def _capture_helper_topics(register: Callable[[object], None]) -> list[str]:
    bus = _RecordingBus()
    # The helpers resolve the bus via module-level get_event_bus(); patch the
    # name where it is bound (it is imported at the top of lifecycle_handlers).
    with mock.patch.object(lifecycle_handlers, "get_event_bus", return_value=bus):
        register(
            object()
        )  # helpers only capture the adapter in a partial; never call it
    return bus.topics


def build_manifest() -> dict:
    services: dict[str, list[str]] = {}
    # Union both keysets so each dict is independently authoritative — a service
    # added to one but not the other must not be silently dropped.
    for service in sorted(set(_LIFECYCLE_HELPERS) | set(_MEMORY_DIRECT)):
        topics: set[str] = set(_MEMORY_DIRECT.get(service, []))
        for register in _LIFECYCLE_HELPERS.get(service, []):
            topics.update(_capture_helper_topics(register))
        services[service] = sorted(topics)
    return {
        "_comment": (
            "Generated by scripts/gen_events_manifest.py — do not edit by hand. "
            "Maps each deployed service to the Pub/Sub topics it subscribes to in "
            "PubSub/SaaS mode; consumed by caura-memclaw-enterprise's "
            "check_pubsub_provisioning.py. Regenerate with: "
            "python scripts/gen_events_manifest.py"
        ),
        "services": services,
    }


def _serialize(manifest: dict) -> str:
    return json.dumps(manifest, indent=2, sort_keys=True) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if the committed manifest is stale instead of writing it.",
    )
    args = parser.parse_args()

    manifest = build_manifest()
    rendered = _serialize(manifest)

    if args.check:
        if not MANIFEST_PATH.exists():
            print(
                f"ERROR: {MANIFEST_PATH} is missing; run scripts/gen_events_manifest.py",
                file=sys.stderr,
            )
            return 1
        current = MANIFEST_PATH.read_text(encoding="utf-8")
        if current != rendered:
            diff = "".join(
                difflib.unified_diff(
                    current.splitlines(keepends=True),
                    rendered.splitlines(keepends=True),
                    fromfile=str(MANIFEST_PATH),
                    tofile="regenerated",
                )
            )
            print(
                f"ERROR: {MANIFEST_PATH.name} is stale. Run: python scripts/gen_events_manifest.py\n{diff}",
                file=sys.stderr,
            )
            return 1
        print(f"{MANIFEST_PATH.name} is up to date.")
        return 0

    MANIFEST_PATH.write_text(rendered, encoding="utf-8")
    print(f"Wrote {MANIFEST_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
